---
## PHP5 FPM #################################################################
- name: Install php5-fpm
  apt: >
    name={{ item }}
    state=present
  with_items:
    - php-apc
    - php-pear
    - php5-cli
    - php5-gd
    - php5-curl
    - php5-fpm
    - php5-mysql
    - php5-mcrypt
  tags:
    - php5-fpm
    - packages

- name: Hardening php.ini
  lineinfile: >
    dest=/etc/php5/fpm/php.ini
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backrefs=yes
  with_items: php_ini_settings
  tags:
    - php5-fpm
    - config

- name: Setting php-fpm unix socket
  lineinfile:
    "dest=/etc/php5/fpm/pool.d/www.conf
    regexp='listen = 127.0.0.1:9000'
    line='listen = /var/run/php-fpm.sock'
    backrefs=yes"
  notify:
    - restart php-fpm
  tags:
    - php5-fpm
    - config

- name: Disabling php5-apc caching if needed
  lineinfile: >
    dest=/etc/php5/fpm/conf.d/apc.ini
    regexp="extension=apc.so"
    line="{{ apc_status }}"
    backrefs=yes
  tags:
    - php5-fpm
    - config

- name: Setting permissions to php-fpm.sock
  lineinfile: >
    dest=/etc/php5/fpm/pool.d/www.conf
    regexp="{{ item.0 }}"
    line="{{ item.1 }}"
    backrefs=yes
  with_items:
    - { 0: ';listen.owner = www-data', 1: 'listen.owner = www-data' }
    - { 0: ';listen.group = www-data', 1: 'listen.group = www-data' }
    - { 0: ';listen.mode = 0666', 1: 'listen.mode = 0666' }
  tags:
    - php5-fpm
    - config

# if error, break the execution and do not restart php (prevents blackouts)
- name: Check php-fpm syntax of configuration files
  command: php5-fpm -t
  register: result
  changed_when: "result.rc != 0"
  notify:
    - restart php-fpm
  tags:
    - php5-fpm

- name: Start the php5-fpm service
  service: name=php5-fpm state=started enabled=yes
  tags:
    - php5-fpm
    - services