---
- name: 1. install MySQL server
  apt: name=mysql-server state=present

- name: 1. install MySQL client
  apt: name=mysql-client state=present

- name: Create Mysql configuration file
  template: src=my.cnf dest=/etc/my.cnf
  notify:
  - restart mysql