---
php_ini_settings:
  - regexp: "memory_limit = 128"
    line: "{{ memory_limit }}"
  - regexp: "post_max_size = 8M"
    line: "{{ post_max_size }}"
  - regexp: "upload_max_filesize = 2M"
    line: "{{ upload_max_filesize }}"
  - regexp: "display_errors = Off"
    line: "{{ display_errors }}"
  - regexp: "error_reporting = E_ALL & ~E_DEPRECATED"
    line: "{{ error_reporting }}"
  - regexp: "display_startup_errors = Off"
    line: "{{ display_startup_errors }}"
  - regexp: "html_errors = Off"
    line: "{{ html_errors }}"
  - regexp: "track_errors = Off"
    line: "{{ track_errors }}"
  - regexp: "session_bug_compat_warn = Off"
    line: "{{ session_bug_compat_warn }}"
  - regexp: ";cgi.fix_pathinfo=1"
    line: "cgi.fix_pathinfo=0"